# https://www.rsyslog.com/doc/v8-stable/tutorials/reliable_forwarding.html

#$ModLoad imuxsock # local message reception
$WorkDirectory /run # default location for work (spool) files

# off box forward
$ActionQueueType LinkedList # use asynchronous processing
$ActionQueueFileName toroot # set file name, also enables disk mode
$ActionResumeRetryCount 10
$ActionQueueSaveOnShutdown on # save in-memory data if rsyslog shuts down
$ActionQueueSize 1024 # max queue entries
$ActionQueueMaxDiskSpace 1M # max disk space
$ActionQueueTimeoutEnqueue 0 # drop when full
*.*   @192.168.10.1:514

# gadget serial forward
$ActionQueueType LinkedList # use asynchronous processing
$ActionQueueFileName tousb # set file name, also enables disk mode
$ActionResumeRetryCount 10
$ActionQueueSaveOnShutdown on # save in-memory data if rsyslog shuts down
$ActionQueueSize 1024 # max queue entries
$ActionQueueMaxDiskSpace 1M # max disk space
$ActionQueueTimeoutEnqueue 0 # drop when full
*.*   /dev/ttyGS0

# nothing else
*.*   stop
