# https://www.rsyslog.com/doc/v8-stable/tutorials/reliable_forwarding.html

#:programname, isequal, "CRON" stop
#cron.info,cron.debug,cron.session stop
if ( $programname == "CRON" and $msg contains "pam_unix(cron:session)" ) then stop
if ( $programname == "exim" and $msg contains "Start queue run" ) then stop
if ( $programname == "exim" and $msg contains "End queue run" ) then stop
if ( $msg contains "action" and $msg contains "resumed" ) then stop

#$ModLoad imuxsock # local message reception
$WorkDirectory /run # default location for work (spool) files

# off box forward
$ActionQueueType LinkedList # use asynchronous processing
$ActionQueueFileName toroot # set file name, also enables disk mode
$ActionResumeRetryCount 10
$ActionQueueSaveOnShutdown on # save in-memory data if rsyslog shuts down
$ActionQueueSize 1024 # max queue entries
$ActionQueueMaxDiskSpace 1M # max disk space
$ActionQueueTimeoutEnqueue 0 # drop when full
*.*   @192.168.10.1:514

# gadget serial forward
#$ActionQueueType LinkedList # use asynchronous processing
#$ActionQueueFileName tousb # set file name, also enables disk mode
#$ActionResumeRetryCount 10
#$ActionQueueSaveOnShutdown off # save in-memory data if rsyslog shuts down
#$ActionQueueSize 1024 # max queue entries
#$ActionQueueMaxDiskSpace 1M # max disk space
#$ActionQueueTimeoutEnqueue 0 # drop when full
#*.*   /dev/ttyGS0

# nothing else
*.*   stop
